collections_dir: content

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false

collections:
  getting-started:
    output: true
  guides:
    output: true
  references:
    output: true
  components:
    output: true
  releases:
    output: true
  comp-releases:
    output: true
  admin:
    output: true
  developers:
    output: true
  on-premises:
    output: true
     
plugins:
  - jekyll-redirect-from

algolia:
  application_id: 'PPVCPBO4V1'
  index_name:     'prod_ava'
  search_only_api_key: 'c90743a840d2d9fd31193ab6180f83cf'

exclude:

  - .jekyll-cache
